language: java

script:
  - "mvn clean install"

jdk:
  - oraclejdk7

services:
  - redis

env:
  - MAVEN_OPTS="-ea -server -Xmx8192m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"

# whitelist
branches:
  only:
    - develop